/**
 * DocForge 文档合成引擎
 * 核心：将 Markdown 内容与模板样式合成专业 DOCX
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Table as DocxTable,
  TableRow,
  TableCell,
  WidthType,
  HeightRule,
  PageBreak
} from 'docx';
import * as fs from 'fs';
import * as path from 'path';
import {
  extractStylesFromDocx,
  getDefaultStyleRules,
  type PythonStyleRules,
} from './python-docx';

/**
 * 样式规则
 */
export interface StyleRule {
  // 字体
  fontFamily?: string;
  fontSize?: number; // 磅值
  fontBold?: boolean;
  fontItalic?: boolean;
  fontColor?: string;

  // 段落
  alignment?: 'left' | 'center' | 'right' | 'justify';
  lineSpacing?: number; // 行距倍数
  spaceBefore?: number;
  spaceAfter?: number;
  indent?: number; // 首行缩进

  // 边框
  borderTop?: boolean;
  borderBottom?: boolean;
  borderLeft?: boolean;
  borderRight?: boolean;
  borderColor?: string;

  // 背景
  shadingColor?: string;
}

/**
 * 样式规则集合
 */
export interface StyleRules {
  title: StyleRule;        // 文档标题
  heading1: StyleRule;     // 一级标题
  heading2: StyleRule;     // 二级标题
  heading3: StyleRule;     // 三级标题
  body: StyleRule;         // 正文
  list: StyleRule;         // 列表
  quote: StyleRule;        // 引用
  code: StyleRule;         // 代码块

  // 页面设置
  pageMargin?: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
  pageOrientation?: 'portrait' | 'landscape';
}

/**
 * 解析后的文档元素
 */
export interface DocElement {
  type: 'title' | 'heading1' | 'heading2' | 'heading3' | 'body' | 'list' | 'quote' | 'code' | 'table' | 'break';
  content: string;
  level?: number;  // 列表层级
  tableData?: string[][];  // 表格数据
}

/**
 * 文档合成引擎
 */
export class DocumentSynthesizer {
  private styleRules: StyleRules;

  constructor(styleRules: StyleRules) {
    this.styleRules = styleRules;
  }

  /**
   * 合成文档
   */
  async synthesize(
    markdown: string,
    outputPath: string,
    options?: {
      addPageBreak?: boolean;
      addTimestamp?: boolean;
    }
  ): Promise<string> {
    // 1. 解析 Markdown 为文档元素
    const elements = this.parseMarkdown(markdown);

    // 2. 将元素转换为 DOCX 段落
    const paragraphs = this.elementsToParagraphs(elements);

    // 3. 如果需要，添加时间戳
    if (options?.addTimestamp) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`,
              size: 18,
              color: 'CCCCCC'
            }),
            new TextRun({
              text: `生成时间：${new Date().toLocaleString('zh-CN')}`,
              size: 18,
              color: '999999'
            })
          ],
          spacing: { before: 200 }
        })
      );
    }

    // 4. 创建 DOCX 文档
    const doc = new Document({
      creator: 'DocForge',
      title: this.extractTitle(elements),
      description: 'Generated by DocForge',
      sections: [{
        properties: {
          page: {
            size: {
              orientation: this.styleRules.pageOrientation || 'portrait'
            },
            margin: this.styleRules.pageMargin || {
              top: 1440,    // 2.5cm (1440 twips = 1 inch)
              bottom: 1440,
              left: 1440,
              right: 1440
            }
          }
        },
        children: paragraphs as any
      }]
    });

    // 5. 生成并保存文件
    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(outputPath, buffer);

    return outputPath;
  }

  /**
   * 解析 Markdown 为文档元素
   */
  private parseMarkdown(markdown: string): DocElement[] {
    const elements: DocElement[] = [];
    const lines = markdown.split('\n');
    let i = 0;

    while (i < lines.length) {
      const line = lines[i].trim();

      // 跳过空行
      if (!line) {
        i++;
        continue;
      }

      // 标题检测（按顺序检测，从长到短）
      if (line.startsWith('### ')) {
        elements.push({ type: 'heading3', content: line.slice(4) });
      } else if (line.startsWith('## ')) {
        elements.push({ type: 'heading2', content: line.slice(3) });
      } else if (line.startsWith('# ')) {
        elements.push({ type: 'title', content: line.slice(2) });
      }
      // 列表检测
      else if (line.match(/^[-*]\s/) || line.match(/^\d+\.\s/)) {
        const level = this.getListLevel(line);
        elements.push({
          type: 'list',
          content: line.replace(/^[-*]\s/, '').replace(/^\d+\.\s/, ''),
          level
        });
      }
      // 引用检测
      else if (line.startsWith('>')) {
        elements.push({ type: 'quote', content: line.slice(1).trim() });
      }
      // 代码块开始
      else if (line.startsWith('```')) {
        let codeContent = '';
        i++;
        while (i < lines.length && !lines[i].startsWith('```')) {
          codeContent += lines[i] + '\n';
          i++;
        }
        elements.push({ type: 'code', content: codeContent.trim() });
      }
      // 分隔线
      else if (line.match(/^[-*]{3,}$/)) {
        elements.push({ type: 'break', content: '' });
      }
      // 表格检测
      else if (line.includes('|') && !line.match(/^\s*[-:]+\s*$/)) {
        const tableData: string[][] = [];
        while (i < lines.length && lines[i].includes('|')) {
          const row = lines[i].split('|').map(c => c.trim()).filter(c => c);
          if (row.length > 1) {
            tableData.push(row);
          }
          i++;
        }
        if (tableData.length > 0) {
          elements.push({ type: 'table', content: '', tableData });
        }
        continue;
      }
      // 普通段落
      else {
        elements.push({ type: 'body', content: line });
      }

      i++;
    }

    return elements;
  }

  /**
   * 获取列表层级
   */
  private getListLevel(line: string): number {
    const spaces = line.match(/^\s*/)?.[0].length || 0;
    return Math.floor(spaces / 240) + 1; // 每 240 twips (约2字符) 一级
  }

  /**
   * 文档元素转换为 DOCX 段落
   */
  private elementsToParagraphs(elements: DocElement[]): (Paragraph | DocxTable | PageBreak)[] {
    const result: (Paragraph | DocxTable | PageBreak)[] = [];

    for (const element of elements) {
      switch (element.type) {
        case 'title':
          result.push(this.createTitleParagraph(element.content));
          break;
        case 'heading1':
          result.push(this.createHeading1(element.content));
          break;
        case 'heading2':
          result.push(this.createHeading2(element.content));
          break;
        case 'heading3':
          result.push(this.createHeading3(element.content));
          break;
        case 'body':
          result.push(this.createBody(element.content));
          break;
        case 'list':
          result.push(this.createListItem(element.content, element.level || 1));
          break;
        case 'quote':
          result.push(this.createQuote(element.content));
          break;
        case 'code':
          result.push(this.createCodeBlock(element.content));
          break;
        case 'break':
          result.push(
            new Paragraph({
              children: [new TextRun({ text: '', size: 1 })],
              border: {
                bottom: { color: 'CCCCCC', space: 3, style: BorderStyle.SINGLE }
              },
              spacing: { before: 200, after: 200 }
            })
          );
          break;
        case 'table':
          if (element.tableData) {
            result.push(this.createTable(element.tableData));
          }
          break;
      }
    }

    return result;
  }

  /**
   * 创建标题段落
   */
  private createTitleParagraph(content: string): Paragraph {
    const s = this.styleRules.title;
    return new Paragraph({
      children: [new TextRun({
        text: content,
        size: (s.fontSize || 22) * 2,
        bold: s.fontBold,
        italics: s.fontItalic,
        color: this.fixColor(s.fontColor),
        font: s.fontFamily ? { name: s.fontFamily } : undefined
      })],
      alignment: this.mapAlignment(s.alignment || 'center'),
      spacing: {
        before: s.spaceBefore || 400,
        after: s.spaceAfter || 300
      }
    });
  }

  /**
   * 创建一级标题
   */
  private createHeading1(content: string): Paragraph {
    const s = this.styleRules.heading1;
    return new Paragraph({
      children: [new TextRun({
        text: content,
        size: (s.fontSize || 16) * 2,
        bold: s.fontBold !== false,
        color: this.fixColor(s.fontColor),
        font: s.fontFamily ? { name: s.fontFamily } : undefined
      })],
      alignment: this.mapAlignment(s.alignment || 'left'),
      spacing: {
        before: s.spaceBefore || 300,
        after: s.spaceAfter || 150
      },
      indent: s.indent ? { firstLine: s.indent } : undefined
    });
  }

  /**
   * 创建二级标题
   */
  private createHeading2(content: string): Paragraph {
    const s = this.styleRules.heading2;
    return new Paragraph({
      children: [new TextRun({
        text: content,
        size: (s.fontSize || 14) * 2,
        bold: s.fontBold !== false,
        color: this.fixColor(s.fontColor),
        font: s.fontFamily ? { name: s.fontFamily } : undefined
      })],
      alignment: this.mapAlignment(s.alignment || 'left'),
      spacing: {
        before: s.spaceBefore || 250,
        after: s.spaceAfter || 100
      },
      indent: s.indent ? { firstLine: s.indent } : undefined
    });
  }

  /**
   * 创建三级标题
   */
  private createHeading3(content: string): Paragraph {
    const s = this.styleRules.heading3;
    return new Paragraph({
      children: [new TextRun({
        text: content,
        size: (s.fontSize || 12) * 2,
        bold: s.fontBold,
        color: this.fixColor(s.fontColor),
        font: s.fontFamily ? { name: s.fontFamily } : undefined
      })],
      alignment: this.mapAlignment(s.alignment || 'left'),
      spacing: {
        before: s.spaceBefore || 200,
        after: s.spaceAfter || 80
      },
      indent: s.indent ? { firstLine: s.indent } : undefined
    });
  }

  /**
   * 创建正文段落
   */
  private createBody(content: string): Paragraph {
    const s = this.styleRules.body;
    return new Paragraph({
      children: [new TextRun({
        text: content,
        size: (s.fontSize || 12) * 2,
        bold: s.fontBold,
        italics: s.fontItalic,
        color: this.fixColor(s.fontColor),
        font: s.fontFamily ? { name: s.fontFamily } : undefined
      })],
      alignment: this.mapAlignment(s.alignment || 'justify'),
      spacing: {
        line: s.lineSpacing ? s.lineSpacing * 240 : undefined,
        before: s.spaceBefore,
        after: s.spaceAfter
      },
      indent: s.indent ? { firstLine: s.indent } : undefined
    });
  }

  /**
   * 创建列表项
   */
  private createListItem(content: string, level: number): Paragraph {
    const s = this.styleRules.list;
    const indent = 240 + (level - 1) * 360; // 每级缩进 0.5cm
    const prefix = '•'; // 可以改为数字或字母

    return new Paragraph({
      children: [
        new TextRun({
          text: prefix + ' ',
          size: (s.fontSize || 12) * 2,
          bold: s.fontBold,
          font: s.fontFamily ? { name: s.fontFamily } : undefined
        }),
        new TextRun({
          text: content,
          size: (s.fontSize || 12) * 2,
          bold: s.fontBold,
          font: s.fontFamily ? { name: s.fontFamily } : undefined
        })
      ],
      alignment: this.mapAlignment(s.alignment || 'left'),
      spacing: { before: s.spaceBefore || 60, after: s.spaceAfter || 60 },
      indent: { left: indent }
    });
  }

  /**
   * 创建引用块
   */
  private createQuote(content: string): Paragraph {
    const s = this.styleRules.quote;
    return new Paragraph({
      children: [new TextRun({
        text: content,
        size: (s.fontSize || 12) * 2,
        italics: s.fontItalic !== false,
        color: this.fixColor(s.fontColor),
        font: s.fontFamily ? { name: s.fontFamily } : undefined
      })],
      indent: { left: s.indent || 720 }, // 缩进 1cm
      border: s.borderLeft ? {
        left: { color: s.borderColor || '999999', space: 6, style: BorderStyle.SINGLE }
      } : undefined,
      shading: s.shadingColor ? { fill: s.shadingColor } : undefined,
      spacing: { before: s.spaceBefore || 100, after: s.spaceAfter || 100 }
    });
  }

  /**
   * 创建代码块
   */
  private createCodeBlock(content: string): Paragraph {
    const s = this.styleRules.code;
    return new Paragraph({
      children: [new TextRun({
        text: content,
        size: (s.fontSize || 11) * 2,
        font: { name: s.fontFamily || 'Consolas' }
      })],
      spacing: { before: s.spaceBefore || 150, after: s.spaceAfter || 150 },
      indent: { left: s.indent || 720 }
    });
  }

  /**
   * 创建表格
   */
  private createTable(data: string[][]): DocxTable {
    const rows = data.map((row, rowIndex) => {
      const isHeader = rowIndex === 0;

      const cells = row.map(cell => {
        return new TableCell({
          children: [new Paragraph({
            children: [new TextRun({
              text: cell,
              size: 24,
              bold: isHeader
            })],
            alignment: AlignmentType.CENTER as any
          })],
          shading: isHeader ? { fill: 'E6E6E6' } : undefined,
          width: { size: 100 / row.length, type: WidthType.PERCENTAGE }
        });
      });

      return new TableRow({
        children: cells,
        height: { value: 360, rule: HeightRule.ATLEAST }
      });
    });

    return new DocxTable({
      rows,
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: '999999' },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: '999999' },
        left: { style: BorderStyle.SINGLE, size: 1, color: '999999' },
        right: { style: BorderStyle.SINGLE, size: 1, color: '999999' },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' }
      }
    });
  }

  /**
   * 提取标题
   */
  private extractTitle(elements: DocElement[]): string {
    const title = elements.find(e => e.type === 'title');
    return title?.content || '无标题文档';
  }

  /**
   * 映射对齐方式
   */
  private mapAlignment(alignment?: string): any {
    switch (alignment) {
      case 'center': return AlignmentType.CENTER;
      case 'right': return AlignmentType.RIGHT;
      case 'justify': return AlignmentType.DISTRIBUTE;
      default: return AlignmentType.LEFT;
    }
  }

  /**
   * 修复颜色格式：确保是 #RRGGBB 格式
   */
  private fixColor(color?: string): string | undefined {
    if (!color) return undefined;
    // 如果已经是 #RRRGGGBBB 格式，去掉 #
    if (!color.startsWith('#')) {
      return '#' + color;
    }
    return color;
  }
}

/**
 * 样式提取器 - 从 DOCX 模板提取样式规则
 */
export class StyleExtractor {
  /**
   * 从 DOCX 文件提取样式规则。
   * DOCX 走 python-docx 真实解析；非 DOCX 模板使用中文正式文档默认样式。
   */
  static async extractFromDocx(docxPath: string): Promise<StyleRules> {
    const ext = path.extname(docxPath).toLowerCase();
    const pythonRules = ext === '.docx'
      ? await extractStylesFromDocx(docxPath)
      : getDefaultStyleRules();

    return this.fromPythonStyleRules(pythonRules);
  }

  private static fromPythonStyleRules(rules: PythonStyleRules): StyleRules {
    const ptToTwips = (pt?: number) => Math.round((pt ?? 0) * 20);
    const inchToTwips = (inch?: number) => Math.round((inch ?? 0) * 1440);
    const paragraph = (key: keyof PythonStyleRules) => (rules[key] as any)?.paragraph || {};
    const font = (key: keyof PythonStyleRules) => (rules[key] as any)?.font || {};

    return {
      title: {
        fontFamily: font('title').name || '黑体',
        fontSize: font('title').size || 22,
        fontBold: font('title').bold !== false,
        fontColor: '#000000',
        alignment: paragraph('title').alignment || 'center',
        lineSpacing: paragraph('title').line_spacing || 1.5,
        spaceBefore: ptToTwips(paragraph('title').space_before ?? 12),
        spaceAfter: ptToTwips(paragraph('title').space_after ?? 6)
      },
      heading1: {
        fontFamily: font('heading1').name || '黑体',
        fontSize: font('heading1').size || 16,
        fontBold: font('heading1').bold !== false,
        fontColor: '#333333',
        alignment: paragraph('heading1').alignment || 'left',
        lineSpacing: paragraph('heading1').line_spacing || 1.5,
        spaceBefore: ptToTwips(paragraph('heading1').space_before ?? 12),
        spaceAfter: ptToTwips(paragraph('heading1').space_after ?? 6),
        indent: 0
      },
      heading2: {
        fontFamily: font('heading2').name || '楷体',
        fontSize: font('heading2').size || 14,
        fontBold: font('heading2').bold !== false,
        fontColor: '#444444',
        alignment: paragraph('heading2').alignment || 'left',
        lineSpacing: paragraph('heading2').line_spacing || 1.5,
        spaceBefore: ptToTwips(paragraph('heading2').space_before ?? 10),
        spaceAfter: ptToTwips(paragraph('heading2').space_after ?? 4),
        indent: 0
      },
      heading3: {
        fontFamily: font('heading3').name || '宋体',
        fontSize: font('heading3').size || 12,
        fontBold: font('heading3').bold !== false,
        fontColor: '#555555',
        alignment: paragraph('heading3').alignment || 'left',
        lineSpacing: paragraph('heading3').line_spacing || 1.5,
        spaceBefore: ptToTwips(paragraph('heading3').space_before ?? 8),
        spaceAfter: ptToTwips(paragraph('heading3').space_after ?? 4),
        indent: 0
      },
      body: {
        fontFamily: font('body').name || '宋体',
        fontSize: font('body').size || 12,
        fontBold: font('body').bold || false,
        fontColor: '#333333',
        alignment: paragraph('body').alignment || 'justify',
        lineSpacing: paragraph('body').line_spacing || 1.5,
        spaceBefore: ptToTwips(paragraph('body').space_before ?? 0),
        spaceAfter: ptToTwips(paragraph('body').space_after ?? 4),
        indent: inchToTwips(paragraph('body').indent_first_line ?? 0.33)
      },
      list: {
        fontFamily: font('list').name || font('body').name || '宋体',
        fontSize: font('list').size || font('body').size || 12,
        fontBold: font('list').bold || false,
        fontColor: '#333333',
        alignment: paragraph('list').alignment || 'left',
        lineSpacing: paragraph('list').line_spacing || 1.5,
        spaceBefore: ptToTwips(paragraph('list').space_before ?? 2),
        spaceAfter: ptToTwips(paragraph('list').space_after ?? 2)
      },
      quote: {
        fontFamily: font('quote').name || '楷体',
        fontSize: font('quote').size || 12,
        fontBold: font('quote').bold || false,
        fontItalic: font('quote').italic !== false,
        fontColor: '#666666',
        alignment: paragraph('quote').alignment || 'left',
        lineSpacing: paragraph('quote').line_spacing || 1.5,
        indent: inchToTwips(paragraph('quote').indent_left ?? 0.4),
        borderLeft: true,
        borderColor: 'CCCCCC',
        shadingColor: 'F5F5F5',
        spaceBefore: ptToTwips(paragraph('quote').space_before ?? 4),
        spaceAfter: ptToTwips(paragraph('quote').space_after ?? 4)
      },
      code: {
        fontFamily: font('code').name || 'Consolas',
        fontSize: font('code').size || 11,
        fontColor: '#333333',
        alignment: paragraph('code').alignment || 'left',
        lineSpacing: paragraph('code').line_spacing || 1.2,
        indent: inchToTwips(paragraph('code').indent_left ?? 0.4),
        spaceBefore: ptToTwips(paragraph('code').space_before ?? 6),
        spaceAfter: ptToTwips(paragraph('code').space_after ?? 6)
      },
      pageMargin: {
        top: inchToTwips(rules.page_margin?.top ?? 1.0),
        bottom: inchToTwips(rules.page_margin?.bottom ?? 1.0),
        left: inchToTwips(rules.page_margin?.left ?? 1.25),
        right: inchToTwips(rules.page_margin?.right ?? 1.25)
      },
      pageOrientation: 'portrait'
    };
  }
}

export default DocumentSynthesizer;
